package com.dcms.CenterServerApp;


/**
* CenterServerApp/CenterServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServer.idl
* Friday, June 15, 2018 at 9:31:03 PM Eastern Daylight Time
*/

public interface CenterServer extends CenterServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CenterServer
